//! Authoritative section type ids, contracts, and codecs.
//!
//! Each registered Rust row type defines one stable `type_id`, logical name,
//! on-disk columns, sort and identity keys, and collection semantics. Layout
//! versions can share a logical name; readers use the contracts to union their
//! columns without guessing from Parquet metadata.
//!
//! The closed [`Section`] trait couples a contract to its encoder, decoder, and
//! timestamp range. The internal `kronika-derive` macro generates those pieces
//! from one annotated struct. [`lint`] rejects invalid ids, keys, and column
//! classes.
//!
//! Encoded and decoded sections are limited to [`MAX_SECTION_BYTES`],
//! [`MAX_SECTION_ROWS`], and [`MAX_ROW_GROUPS`]. [`VerifiedSection`] requires a
//! caller-supplied CRC check before Parquet sees the bytes. These checks bound
//! ordinary resource use and accidental corruption; they do not authenticate
//! a deliberately rebuilt segment.
//!
//! `PostgreSQL`- and Linux-specific meaning belongs here in declarative
//! contracts. Collection, storage, cross-segment queries, and HTTP responses
//! belong to their respective crates.
#[cfg(test)]
use serde_json as _;

// The codec generated by `#[derive(Section)]` refers to this crate by name,
// so it must be nameable from inside the crate too.
extern crate self as kronika_registry;

mod catalog;
mod codec;
mod contract;
mod generic;
mod parquet_preflight;
mod pool;
mod section;
mod type_id;

pub use catalog::{
    DICT_BLOBS_TYPE_ID, DICT_STRINGS_TYPE_ID, contract, logical_section_name, registry,
    section_implementation, section_name,
};

// Closes `Section` to downstream impls while keeping the public trait usable as
// a bound.
mod private {
    #[allow(
        unnameable_types,
        reason = "closing Section means Private is reachable (as its supertrait) but deliberately not nameable downstream"
    )]
    pub trait Private {}
}

pub use codec::{
    CodecError, DecodeStats, DecodedSection, FINAL_DATA_PAGE_BYTES, FINAL_ZSTD_LEVEL,
    FinalPlainColumnSize, ListColumn, MAX_DECODED_SECTION_BYTES, MAX_ROW_GROUPS, MAX_SECTION_BYTES,
    MAX_SECTION_ROWS, SECTION_WRITE_BATCH_ROWS, VerifiedSection, arrow_schema,
    encode_final_batches, encode_final_sections_to, final_data_body_bound,
    final_single_batch_plain_body_bound, nullable_bool, nullable_column, opt_bool, opt_primitive,
    read_list_i32, required_bool, required_column, validate_final_section, write_bool,
    write_bool_nullable, write_list_i32, write_nullable, write_required,
};
pub use parquet_preflight::{
    ParquetDecodeProfile, parquet_decode_profile, plain_parquet_decode_profile,
    validate_parquet_decode_work, validate_plain_parquet_decode_work,
};
// Only the in-crate derive and tests need the shared section-body entry points.
pub use arrow_array::RecordBatch;
pub use codec::pg_locks::{PgLocksV1, PgLocksV2};
pub use codec::pg_log::{
    PgLogAutovacuum, PgLogCheckpoints, PgLogErrors, PgLogLifecycle, PgLogLockWaits,
    PgLogSlowQueries, PgLogTempFiles,
};
pub use codec::pg_prepared_xacts::PgPreparedXacts;
pub use codec::pg_settings::PgSettings;
pub use codec::pg_stat_activity::{PgStatActivityV1, PgStatActivityV2, PgStatActivityV3};
pub use codec::pg_stat_archiver::PgStatArchiver;
pub use codec::pg_stat_bgwriter::{PgStatBgwriterV1, PgStatBgwriterV2};
pub use codec::pg_stat_checkpointer::{PgStatCheckpointerV1, PgStatCheckpointerV2};
pub use codec::pg_stat_database::{
    PgStatDatabaseV1, PgStatDatabaseV2, PgStatDatabaseV3, PgStatDatabaseV4,
};
pub use codec::pg_stat_io::{PgStatIoV1, PgStatIoV2};
pub use codec::pg_stat_progress_vacuum::{
    PgStatProgressVacuumV1, PgStatProgressVacuumV2, PgStatProgressVacuumV3,
};
pub use codec::pg_stat_statements::{
    PgStatStatementsV1, PgStatStatementsV2, PgStatStatementsV3, PgStatStatementsV4,
    PgStatStatementsV5, PgStatStatementsV6,
};
pub use codec::pg_stat_statements_info::PgStatStatementsInfo;
pub use codec::pg_stat_user_indexes::{PgStatUserIndexesV1, PgStatUserIndexesV2};
pub use codec::pg_stat_user_tables::{
    PgStatUserTablesV1, PgStatUserTablesV2, PgStatUserTablesV3, PgStatUserTablesV4,
};
pub use codec::pg_stat_wal::{PgStatWalV1, PgStatWalV2};
pub use codec::pg_store_plans::{
    PgStorePlansDatasentinelV1, PgStorePlansOsscV1, PgStorePlansVadvV1,
};
pub use codec::pg_store_plans_info::PgStorePlansInfo;
pub use codec::pg_wal_storage::PgWalStorage;
pub use codec::pgbouncer_events::PgBouncerEvents;
pub(crate) use codec::{check_row_cap, decode_batches, decode_section, encode_section};
pub use codec::{
    instance_metadata, os_block_topology, os_cgroup_context, os_cgroup_cpu, os_cgroup_io,
    os_cgroup_mapping, os_cgroup_memory, os_cgroup_pids, os_cgroup_v2_cpu, os_cgroup_v2_group,
    os_cgroup_v2_io, os_cgroup_v2_memory, os_cgroup_v2_pids, os_cpu, os_cpufreq, os_diskstats,
    os_interrupts, os_kernel_limits, os_loadavg, os_meminfo, os_mountinfo, os_netdev, os_netstat,
    os_nfs, os_numa, os_process, os_process_status, os_psi, os_snmp, os_snmp6, os_softirq, os_stat,
    os_topology, os_user, os_vmstat, pg_locks, pg_log, pg_prepared_xacts, pg_settings,
    pg_stat_activity, pg_stat_archiver, pg_stat_bgwriter, pg_stat_checkpointer, pg_stat_database,
    pg_stat_io, pg_stat_progress_vacuum, pg_stat_statements, pg_stat_statements_info,
    pg_stat_user_indexes, pg_stat_user_tables, pg_stat_wal, pg_store_plans, pg_store_plans_info,
    pg_wal_storage, pgbouncer_events,
};
pub use contract::{
    Column, ColumnClass, ColumnType, LintError, Semantics, StrId, Ts, TypeContract, Unit, lint,
};
pub use generic::{Cell, Row, decode_rows, visit_batches, visit_rows};
pub use pool::{BytesPool, PoolStats};
pub use section::Section;
#[cfg(test)]
pub(crate) use test_support::assert_roundtrips;

#[cfg(test)]
#[path = "tests/support.rs"]
mod test_support;
pub use type_id::{SectionClass, TypeId};

// One `Bytes` for the decode API and derived codecs to name.
pub use bytes::Bytes;

// Section types are defined in this crate; the derive macro is not exported.
pub(crate) use kronika_derive::Section;

// Type tokens named by generated codecs.
pub use arrow_array::types::{
    Float32Type, Float64Type, Int8Type, Int16Type, Int32Type, Int64Type, UInt8Type, UInt16Type,
    UInt32Type, UInt64Type,
};

/// Decode a verified section body using the contract selected by `type_id`.
///
/// # Errors
///
/// Returns [`CodecError`] for unknown `type_id`, schema mismatch, caps, or
/// Parquet decode failures.
pub fn decode_any(type_id: u32, section: VerifiedSection) -> Result<DecodedSection, CodecError> {
    let contract = contract(type_id).ok_or(CodecError::UnknownType { type_id })?;
    let bytes_in = section.len();
    decode_batches(contract, section).map_err(|source| CodecError::Section {
        type_id,
        bytes_in,
        source: Box::new(source),
    })
}

/// Decode a section read into a pooled buffer.
///
/// # Errors
///
/// Returns [`CodecError`] when length, CRC, type lookup, or decoding fails.
pub fn decode_pooled(
    pool: &BytesPool,
    type_id: u32,
    expected_len: usize,
    expected_crc: u32,
    crc32c: impl FnOnce(&[u8]) -> u32,
    fill: impl FnOnce(&mut Vec<u8>),
) -> Result<DecodedSection, CodecError> {
    if expected_len > MAX_SECTION_BYTES {
        return Err(CodecError::SectionTooLarge {
            len: expected_len,
            max: MAX_SECTION_BYTES,
        });
    }
    let bytes = pool.load(fill);
    // Guard against a buggy fill that writes more than the caller announced.
    if bytes.len() > MAX_SECTION_BYTES {
        return Err(CodecError::SectionTooLarge {
            len: bytes.len(),
            max: MAX_SECTION_BYTES,
        });
    }
    let bytes_in = bytes.len();
    let section = VerifiedSection::verify(bytes, expected_crc, crc32c).map_err(|source| {
        CodecError::Section {
            type_id,
            bytes_in,
            source: Box::new(source),
        }
    })?;
    decode_any(type_id, section)
}

/// Run the registry linter over every known type.
///
/// # Errors
///
/// Returns all linter errors found in registered contracts.
pub fn lint_registry() -> Result<(), Vec<LintError>> {
    lint(registry())
}

#[cfg(test)]
#[path = "tests/registry.rs"]
mod tests;
